kind: ConfigMap
apiVersion: v1
metadata:
  name: app-config-rhdh
data:
  app-config-rhdh.yaml: |
    app:
      title: My Red Hat Developer Hub
      baseUrl: https://redhat-developer-hub-{your_sandbox_project}.apps.{your_sandbox_url}.openshiftapps.com/
    integrations:
     github:
       - host: github.com
         token: {YOUR ACCESS_TOKEN}
    auth:
     allowGuestAccess: true
     environment: development
     providers:
       github:
         development:
           clientId: {YOUR CLIENT_ID}
           clientSecret: {YOUR Client Secrets}
    enabled:
      github: true